import type { Metadata } from "next";
import { Arimo, League_Gothic } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const arimo = Arimo({
  subsets: ["latin"],
  weight: ["400", "700"], 
  variable: "--font-arimo",
});

const leagueGothic = League_Gothic({
  subsets: ["latin"],
  weight: ["400"], 
  variable: "--font-league-gothic",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arimo.variable} ${leagueGothic.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
